"""Chat service — orchestrates memory, rate limiting, and the RAG pipeline (RC-102).

Sits between chat/router.py (thin HTTP layer) and rag/pipeline.py (RAG logic).
Mirrors the auth/service.py pattern: business logic lives here, not in the router.

Execution order:
    1. Hourly rate limit check  → HTTP 429 if exceeded
    2. Daily rate limit check   → HTTP 429 if exceeded
    3. Load session history     from Redis
    4. Run RAG pipeline         in thread pool (non-blocking)
    5. Save human+AI turn       to Redis (only on success)
    6. Annotate LangSmith trace with session metadata
    7. Return ChatResponse
"""
from __future__ import annotations

import asyncio
import uuid

import redis as redis_lib
from fastapi import HTTPException

from app.auth.schemas import UserContext
from app.chat.schemas import ChatRequest, ChatResponse
from app.config import settings
from app.guardrails import GuardBlockedError
from app.memory.session import get_history, save_turn
from app.rag.pipeline import RagResult, run_rag
from app.rag.retriever import RetrieverUnavailableError
from app.rate_limit.limiter import check_and_increment, get_hourly_limit


async def handle_chat(
    request: ChatRequest,
    session_id: str,
    user_context: UserContext,
    redis: redis_lib.Redis,
) -> ChatResponse:
    """Full chat pipeline: rate check → load history → RAG → save turn → return.

    Args:
        request:      Validated ChatRequest (question + optional session_id).
        session_id:   Resolved session identifier (generated by router if absent).
        user_context: Authenticated user extracted from the Bearer JWT.
        redis:        Shared Redis client injected via RedisDep.

    Raises:
        HTTPException(429): Hourly or daily rate limit exceeded.
        HTTPException(400): Input guardrail blocked the query.
        HTTPException(503): Vector search backend unavailable.
        HTTPException(500): Unexpected internal error.
    """
    request_id = str(uuid.uuid4())

    # ------------------------------------------------------------------
    # 1. Rate limit — hourly (per-role)
    # ------------------------------------------------------------------
    hourly_limit = get_hourly_limit(user_context.role)
    if not check_and_increment(redis, user_context.user_id, 3600, hourly_limit):
        raise HTTPException(
            status_code=429,
            headers={"Retry-After": "3600"},
            detail={
                "error": True,
                "code": "RATE_LIMIT_EXCEEDED",
                "message": (
                    "You have exceeded the query limit. "
                    "Please wait before trying again."
                ),
                "retry_after_seconds": 3600,
            },
        )

    # ------------------------------------------------------------------
    # 2. Rate limit — daily (all roles)
    # ------------------------------------------------------------------
    daily_limit = settings.rate_limit_default_per_day
    if not check_and_increment(redis, user_context.user_id, 86400, daily_limit):
        raise HTTPException(
            status_code=429,
            headers={"Retry-After": "86400"},
            detail={
                "error": True,
                "code": "RATE_LIMIT_EXCEEDED",
                "message": (
                    "You have exceeded the daily query limit. "
                    "Please try again tomorrow."
                ),
                "retry_after_seconds": 86400,
            },
        )

    # ------------------------------------------------------------------
    # 3. Load session history from Redis
    # ------------------------------------------------------------------
    session_history = get_history(redis, session_id)
    turn_index = len(session_history) // 2   # number of complete prior exchanges

    # ------------------------------------------------------------------
    # 4. RAG pipeline — run in thread pool (sync → async)
    # ------------------------------------------------------------------
    try:
        result: RagResult = await asyncio.to_thread(
            run_rag,
            request.question,
            user_context.role,
            session_history,
        )
    except GuardBlockedError as exc:
        raise HTTPException(
            status_code=400,
            detail={"error": exc.reason, "message": exc.message},
        )
    except RetrieverUnavailableError:
        raise HTTPException(
            status_code=503,
            detail={
                "error": "search_unavailable",
                "message": (
                    "The search service is temporarily unavailable. "
                    "Please try again shortly."
                ),
                "request_id": request_id,
            },
        )
    except Exception:
        raise HTTPException(
            status_code=500,
            detail={
                "error": "internal_error",
                "message": "An unexpected error occurred. Please try again shortly.",
                "request_id": request_id,
            },
        )

    # ------------------------------------------------------------------
    # 5. Save turn — only on successful RAG response
    # ------------------------------------------------------------------
    save_turn(redis, session_id, request.question, result.answer)

    # ------------------------------------------------------------------
    # 6. Annotate LangSmith trace with session + memory metadata
    # ------------------------------------------------------------------
    _annotate_langsmith(
        session_id=session_id,
        turn_index=turn_index,
        history_length=len(session_history),
        user_role=user_context.role,
    )

    # ------------------------------------------------------------------
    # 7. Return response
    # ------------------------------------------------------------------
    return ChatResponse(
        answer=result.answer,
        sources=result.sources,
        session_id=session_id,
        run_id=result.run_id,
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _annotate_langsmith(
    session_id: str,
    turn_index: int,
    history_length: int,
    user_role: str,
) -> None:
    """Best-effort LangSmith run tree annotation.  Never raises."""
    try:
        import langsmith
        run_tree = langsmith.get_current_run_tree()
        if run_tree is not None:
            run_tree.metadata.update(
                {
                    "session_id": session_id,
                    "turn_index": turn_index,
                    "history_length": history_length,
                    "user_role": user_role,
                }
            )
    except Exception:
        pass
